//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsSample.Repositories.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviePerson
    {
        public int Id { get; set; }
        public bool Active { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BirthPlace { get; set; }
        public System.DateTimeOffset Birthday { get; set; }
        public string Biography { get; set; }
        public string PhotoUrl { get; set; }
        public string IMDBUrl { get; set; }
        public int Popularity { get; set; }
        public System.DateTimeOffset DateCreated { get; set; }
        public int UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> LastModified { get; set; }
        public Nullable<int> UserLastModified { get; set; }
    }
}
