//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsSample.Repositories.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieRating
    {
        public int MovieId { get; set; }
        public int UserRatedId { get; set; }
        public System.DateTimeOffset DateCreated { get; set; }
        public int UserCreated { get; set; }
        public int Rating { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
